add slice escaping
streamingfast/substreams-sink-sql pull request #23
Opened 2023-06-06 16:03 UTC by flametuner

When trying to use BYTES column in postgres, substreams uses Vec and the conversion process to Go translates to a Slice. Postgres needs escaped bytes the same as strings.

2023-06-06 18:03 UTC, maoueh requested changes
Seems good otherwise

2023-06-06 18:03 UTC, maoueh commented on db/operations.go
> +		return escapeStringValue(value), nil
Let's add a CHANGELOG entry

2023-06-06 18:24 UTC, flametuner commented on db/operations.go
> +		return escapeStringValue(value), nil
Ohh, I always forget hahahaha.

2023-06-07 14:01 UTC, maoueh approved these changes

2023-06-07 14:01 UTC, merged