feat: add rollback sinker
streamingfast/substreams-sink-sql pull request #32
Opened 2023-07-28 14:51 UTC by pedrotambo

2023-08-23 20:04 UTC, maoueh requested changes

2023-08-23 20:04 UTC, maoueh commented on cmd/substreams-sink-postgres/run.go
>  	}()
We should create a rollback sinker only if `rollback-url` is set, otherwise use the standard `sinker`.

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +	}
Let's perform this validation in the `New` directly and always assume here that we are properly set up.

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +	u, _ := url.ParseRequestURI(s.rollbackUrl)
The `New` should also validate that the `rollbackUrl` passes `ParseRequestURI`.

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +	params.Add("schema", s.rollbackSchema)
Shouldn't we send the full DSN components (expect the password) so we wouldn't need `rollbackSchema`?

Or maybe `rollbackSchema` is some different schema than the one of the DSN?

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +	resp, err := http.Get(urlStr)
```suggestion
	resp, err := http.Get(u.String())
```

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +		return fmt.Errorf("Rollback failed")
```suggestion
		return fmt.Errorf("rollback failed: %w", err)
```

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +		return fmt.Errorf("Error reading response body")
```suggestion
		return fmt.Errorf("reading response body: %w", err)
```

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +
```suggestion
    defer resp.Body.Close()
```

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +	resp.Body.Close()
```suggestion
```

Removed, done as `defer resp.Body.Close()` to ensure it's always done.

2023-08-23 20:04 UTC, maoueh commented on rollback_sinker/rollback_sinker.go
> +	s.logger.Info(string(body))
```suggestion
	fields := []zap.Field{zap.String("status", resp.Status)}
	if s.logger.Core().Enabled(zap.DebugLevel) {
		fields = append(fields, zap.ByteString("body", body))
	}
	s.logger.Info("completed rollback successfully", fields...)
```

2023-08-23 20:04 UTC, maoueh commented on cmd/substreams-sink-postgres/run.go
> +		flags.String("rollback-db-schema", "", "schema rollback service")
I'm thinking about supporting different rollbacks techniques in the future so I'll probably revisit how we enable the correct "rollback handler" before shipping the feature in an official release.

2023-12-04 21:41 UTC, sduchesneau commented
@pedrotambo the postgresql endpoint supports the reorgs natively now. Can we close this PR ?

2023-12-05 15:19 UTC, closed without merging