fixed Clickhouse Array type
streamingfast/substreams-sink-sql pull request #72
Opened 2024-11-06 13:47 UTC by fschoell

2024-12-02 18:34 UTC, maoueh requested changes

2024-12-02 18:34 UTC, maoueh commented on db/dialect_clickhouse.go
> +		}
The `valueType` is coming from `o.table.columnsByName[v].scanType` which seems to be bound in terms of lifecycle to the actual schema.

Could we perform this check earlier on?

2024-12-02 18:34 UTC, maoueh commented on db/dialect_clickhouse.go
> +			return "", fmt.Errorf("could not unmarshal slice value %q: %w", value, err)
```suggestion
			return "", fmt.Errorf("could not JSON unmarshal slice value %q: %w", value, err)
```

2024-12-19 11:50 UTC, fschoell commented on db/dialect_clickhouse.go
> +		}
the scan is happening in the database agnostic part, so I don't think we should move a Clickhouse specific validation in there.

2024-12-21 20:13 UTC, merged